name: decodeshare
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch>=2.2
  - pytorch-cuda=12.1
  - numpy>=1.26,<3
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pip:
      - -e .[dev]
